enrico-dev/enrico

- .readthedocs.yml
- doc/source/conf.py
- doc/source/requirements.txt
This has all the configuration needed to build on readthedocs.io.  As an example, the docs for this branch are built at https://enrico-docs.readthedocs.io/en/readthedocs/.  Once this is merged into master, I'll set up readthedocs so it builds for the master branch instead of this one.
> Read the Docs

- doc/source/conf.py
- doc/source/index.rst
- doc/source/input.rst
- doc/source/requirements.txt
One thing sorely missing from our documentation (that would absolutely be needed by a user) is a description of what's in `enrico.xml`. This PR adds it.
> Add section in documentation describing enrico.xml

- CMakeLists.txt
This dates back to when gslib was a subtree instead of a submodule.
> Removed nonexistent (hence unneeded) include dir from CMake

- CMakeLists.txt
- include/smrt/shift_driver.h
- include/smrt/shift_nek_driver.h
- src/smrt/Multiphysics_Driver.cpp
- src/smrt/shift_driver.cpp
- src/smrt/shift_nek_driver.cpp
- tests/singlerod/short/test_shift_coupled.cpp
Moving !94 from gitlab originally submitted by @aprilnovak:
This PR adds consistent class naming for the Shift-related drivers (based on the conventions used on the OpenMC side of things, but either way is fine).
Also, I made a few minor changes in `ShiftNekDriver` to begin the base class consolidation process, such as always assuming that the coupling input file is named `enrico.xml` and making available `power_` and `max_timesteps_` member variables that will later be moved from `ShiftNekDriver` to `CoupledDriver`.
Since I don't have SCALE yet I couldn't compile this, but finger's crossed I didn't make any mistakes.
> Consistent class naming

- tests/comm_split_demo/main.cpp
Doesn't affect ENRICO core, but gives an error with "make all" on my MacBook.  This was the better macro to use, anyway.
> HOST_NAME_MAX -> _POSIX_HOST_NAME_MAX

- include/smrt/Assembly_Model.h
- include/smrt/Multi_Pin_Subchannel.h
- include/smrt/Single_Pin_Conduction.h
- include/smrt/Single_Pin_Subchannel.h
- include/smrt/Two_Group_Diffusion.h
- src/coupled_driver.cpp
- src/smrt/Assembly_Model.cpp
- src/smrt/Multi_Pin_Conduction.cpp
- src/smrt/Multi_Pin_Subchannel.cpp
- src/smrt/Multiphysics_Driver.cpp
- src/smrt/Single_Pin_Conduction.cpp
- src/smrt/Single_Pin_Subchannel.cpp
- src/smrt/Two_Group_Cross_Sections.cpp
- src/smrt/Two_Group_Diffusion.cpp
- src/smrt/Water_Properties.cpp
- src/smrt/shift_driver.cpp
- src/smrt/shift_nek_driver.cpp
@sphamil and I discussed stripping out external dependencies for the surrogate solvers that appear in the smrt directory. One of the changes needed is to use assertion macros from GSL (which is already in our repo) rather than the existing assertion macros that are being used (from SCALE). I've made the following changes:
- Precondition: `Requires` is now `Expects`
- General invariant: `Check` is now `Expects`
- Input validation: `Validate` is now `Expects` (had to remove error message, but we agreed this is not a big deal)
- Postcondition: `Ensure` is now `Ensures`
@sphamil Can you try compiling and make sure that I haven't broken anything?
> Use assertions from GSL in SMRT files

- include/enrico/coupled_driver.h
- include/enrico/openmc_heat_driver.h
- include/enrico/openmc_nek_driver.h
- src/coupled_driver.cpp
- src/openmc_heat_driver.cpp
- src/openmc_nek_driver.cpp
Both `OpenmcHeatDriver` and `OpenmcNekDriver` implemented their own convergence checks, which were identical. This MR moves the convergence check to the `CoupledDriver` class. In addition, a `has_global_coupling_data()` method is added to ensure that the convergence check is only called from ranks that have access to the global coupling solution fields, since that might differ in the future between `OpenmcHeatDriver` and `OpenmcNekDriver`.
> Move convergence check

- CMakeLists.txt
- include/enrico/message_passing.h
- include/enrico/neutronics_driver.h
- include/enrico/openmc_driver.h
- include/enrico/openmc_heat_driver.h
- include/enrico/openmc_nek_driver.h
- include/smrt/Neutronics_Solver.h
- include/smrt/shift_driver.h
- include/smrt/shift_nek_driver.h
- include/smrt/smrt_coupled_driver.h
- src/message_passing.cpp
- src/openmc_driver.cpp
- src/openmc_nek_driver.cpp
- src/smrt/shift_driver.cpp
- src/smrt/shift_nek_driver.cpp
- src/smrt/smrt_coupled_driver.cpp
This PR has a couple first steps in eventually having `ShiftNekDriver` derive from `CoupledDriver`. This PR adds:
1. Mostly empty `SmrtCoupledDriver` class to assist in incremental updates to `ShiftNekDriver` so that we will eventually be able to replace `SmrtCoupledDriver` by `CoupledDriver`.
2. Split out some actions from the `solve` methods of `smrt` classes into more specific, smaller tasks.
3. Moved the definition of the position MPI datatype to `message_passing.h` since it's used equivalently by `ShiftNekDriver` and `OpenmcNekDriver`.
@sphamil would you please verify that this compiles? Hopefully I didn't leave any typos...
> Smrt enrico consolidation

- doc/source/input.rst
- include/enrico/cell_instance.h
- include/enrico/coupled_driver.h
- include/enrico/openmc_nek_driver.h
- src/cell_instance.cpp
- src/coupled_driver.cpp
- src/openmc_nek_driver.cpp
This MR defines the `densities_` and `densities_prev_` members in `CoupledDriver` in a similar manner to how we define temperatures and the heat source.
This MR updates `OpenmcNekDriver` to set the initial densities either from the OpenMC input or from the Nek restart file (by calling IAPWS on a restart temperature with pressure BC). This will permit accurate estimates of convergence based on density between the first and second iterations if we decide to use that.
This is marked as WIP until !1254 is merged into OpenMC and we do a submodule update here.
> Set density IC in OpenmcNekDriver

- include/enrico/coupled_driver.h
- include/enrico/heat_fluids_driver.h
- include/enrico/nek_driver.h
- include/enrico/openmc_heat_driver.h
- include/enrico/openmc_nek_driver.h
- include/enrico/surrogate_heat_driver.h
- src/coupled_driver.cpp
- src/openmc_heat_driver.cpp
- src/openmc_nek_driver.cpp
This MR adds temperature underrelaxation to the `CoupledDriver`, which moves the saving and setting of `temperatures_` and `temperatures_prev_` to the `CoupledDriver` such that its derived classes only need to define `set_temperature()` based on mappings between the two physics tools.
> Temperature relaxation

- include/smrt/Multi_Pin_Subchannel.h
- src/smrt/Multi_Pin_Subchannel.cpp
- src/smrt/Multiphysics_Driver.cpp
To increase similarity to the `HeatFluidsDriver` base class, this MR adds private temperature and density members to the `Multi_Pin_Subchannel` solver that are explicitly retrieved from the `Multiphysics_Driver` class.
A private `pin_powers` member is also added that in the future will be explicitly updated by a coupled driver instead of within the `solve` method [but I didn't do that here to keep things small to try to get successful compilation :) ].
> Add Multi_Pin_Subchannel member variables

- doc/source/input.rst
- src/openmc_driver.cpp
- src/openmc_heat_driver.cpp
- src/surrogate_heat_driver.cpp
- src/vtk_viz.cpp
The primary purpose of this PR is to fix a few bugs when running the heat surrogate model with multiple pins. I also changed the filename format for OpenMC statepoints to `openmc_t#_i#.h5` to indicate "timestep" and "iteration" (same thing for viz files).
@pshriwise can you take a look at my fixes in vtk_viz.cpp to see if they make sense to you?
> Fixes for heat surrogate with multiple pins

- CMakeLists.txt
- src/openmc_nek_driver.cpp
- src/surrogate_heat_driver.cpp
This PR:
- Fixes some compile warnings that clang gives
- Ensures that ENRICO is built with `-dynamic` on BG/Q instead of `-rdynamic`
> Fix some compile warnings

- include/enrico/openmc_driver.h
- include/enrico/openmc_nek_driver.h
- src/openmc_nek_driver.cpp
This change stemmed from a bug that I found when trying to run our coupled short assembly model. Namely, `heat_index_` was being allocated to be the size of `openmc_driver_->cells_` (i.e., the number of materials that are found by searching using Nek5000 element centroids) but was then being indexed with an OpenMC material index (which might be larger than the size of `cells_`. My fix was to just use the index in `cells_` instead, since the cell instance knows its corresponding material index. After making this change, I realized that `heat_index_` is was not actually needed at all anymore, so it has been removed.
Along with this change, I've renamed all the mappings to reference "cells" rather than "materials". I'm planning on implementing a "cell instance" filter in OpenMC that will …
> Use cell instances for Nek <-> OpenMC mappings

- include/enrico/neutronics_driver.h
- include/enrico/openmc_driver.h
- include/smrt/shift_driver.h
- include/smrt/shift_nek_driver.h
- src/openmc_driver.cpp
- src/smrt/shift_driver.cpp
- src/smrt/shift_nek_driver.cpp
For the neutronics smrt drivers to act as "black-boxes," they shouldn't require any data mapping information from Nek/surrogates. This MR moves the power normalization into `ShiftDriver` based on the Shift geometry (i.e. according to cell volumes). The `ShiftNekDriver` is changed to grab the power from the Shift driver and apply it to Nek's elements according to the established coupling mappings.
In the future, I see this progressing to the point where `d_power_map` is not created by `ShiftDriver` at all, but instead in `ShiftNekDriver`, since it reflects coupling info, not single-physics info.
I haven't compiled this yet FYI, so this is just a proposed idea.
> Move power normalization into ShiftDriver

- include/enrico/openmc_nek_driver.h
- src/openmc_nek_driver.cpp
There was evidently a bug in the OpenMC-Nek mapping introduced by #39 (namely, [this line](https://github.com/enrico-dev/enrico/blob/bb4f302d4820841e484745cfacf14179bca719de/src/openmc_nek_driver.cpp#L142)). This PR fixes that bug and adds a volume check that shows the volumes reported by OpenMC and Nek that can help to identify such issues in the future.
> Fix mapping of OpenMC cell instances to Nek elements

- include/enrico/nek_driver.h
- include/enrico/openmc_nek_driver.h
- src/nek_driver.cpp
- src/openmc_nek_driver.cpp
This is a second pass at #54.  The changes can be summarized as follows:
* The Nek interface (C and Fortran) has been updated to use `int32_t` for indices.  The submodule has been updated accordingly.  
* In ENRICO, loop indices that are used to index Nek arrays are declared as `int32_t`.  `gsl::index` isn't really appropriate here, since the Nek arrays can only be as long as an int32.  
* Loop indices that are used to index `std::vector` and xtensors are declared as `gsl::index`
> Integer types in Nek interface, drivers

- include/enrico/cell_instance.h
- include/enrico/openmc_driver.h
- src/cell_instance.cpp
- src/openmc_driver.cpp
- src/openmc_heat_driver.cpp
This MR adds two sanity checks to the `OpenmcHeatDriver::init_mappings()`:
1. The number of tracked OpenMC cells in the pellet regions must equal the number of total fissionable cells. This ensures that the surrogate mesh is sufficiently fine to "find" all the OpenMC cells with our collocation-type search. This implicitly assumes you'll be coupling anywhere you have fissionable material.
2. The cells in the pellet and cladding should be fissionable and not fissionable, respectively. This additional check helps ensure that the models line up geometrically by matching OpenMC fissile cells to where those cells actually are in the T/H model.
Marked as WIP until !1310 in OpenMC is merged to access the `cells_size()` method.
> Check fissionable cells in Openmc-surrogate

- include/enrico/openmc_heat_driver.h
- include/enrico/surrogate_heat_driver.h
- src/openmc_driver.cpp
- src/openmc_heat_driver.cpp
- src/surrogate_heat_driver.cpp
- src/vtk_viz.cpp
This MR adds use of the subchannel fluid temperature and density solutions in OpenMC for the `OpenmcHeatDriver`. Auxiliary features include:
1. Ability to set initial density based on OpencMC model
2. Ability to set initial fluid temperature based on OpenMC model
This MR doesn't include any checks on convergence based on density or fluid temperature, which I think should be added as a separate commit. In the design here, I found it easier to work with temperatures and densities for the fluid and solid separately so that not a whole lot of reworking was needed for the existing solid solution. This results in the `fluid_mask` being un-used. I think this is fine for now, but I envision in the future moving `fluid_mask` out of the T/H base class and into `NekDriver`, _or_ changing the …
> Use subchannel in OpenmcHeatDriver

- include/enrico/heat_fluids_driver.h
- include/enrico/nek_driver.h
- include/enrico/surrogate_heat_driver.h
- src/openmc_heat_driver.cpp
- src/surrogate_heat_driver.cpp
Not all T/H drivers compute solid density, so it is not always necessary to compute a `fluid_mask` to pick out the fluid entries in the density solution. This PR changes the `fluid_mask` to be a member of `NekDriver` instead of the base T/H driver class.
> Make fluid_mask optional and leave interpretation of density to the solver

- CMakeLists.txt
- include/smrt/shift_heat_fluids_driver.hpp
- src/smrt/shift_heat_fluids_driver.cpp
This MR removes surrogate-surrogate coupling in `smrt` to match convention used elsewhere in this project by having each coupled-physics driver drive only two (pre-defined) applications. Previously, `Multiphysics_Driver` selected the neutronics solver in its constructor. This is removed so that `Multiphysics_Driver` only couples Shift and a T/H surrogate (and hence is renamed to `ShiftHeatFluidsDriver`.
This may break some tests or input files on the ORNL side that used the `Multiphysics_Driver` constructor to select the neutronics solver - that selection should be moved outside to a `main.cpp` or some other higher-level driver (I just don't have access to that yet).
> Remove surrogate-surrogate coupling

- .gitignore
- ci/patch_singlerod_rea.sh
I use `ci/patch_singlerod_rea.sh` pretty often when I'm developing locally.  It was written for a CI build matrix, and it ran `patch` only if the env variable `$MODE` equaled `openmc_nek5000`.  I changed it so it also runs `patch` if `$MODE` is undefined, which is more convenient when you run it manually.  Shouldn't ruin the CI build matrix, since `$MODE` is always set to something there.
> Updates to patch_singlerod_rea.sh

- doc/source/input.rst
- include/enrico/coupled_driver.h
- include/enrico/openmc_heat_driver.h
- include/enrico/openmc_nek_driver.h
- src/coupled_driver.cpp
- src/openmc_heat_driver.cpp
- src/openmc_nek_driver.cpp
This MR applies relaxation to the density field, so now the interface for updating and setting coupled fields is uniform across the heat source, temperatures, and densities.
> Density relaxation

- .gitmodules
- CMakeLists.txt
- doc/source/input.rst
- include/enrico/neutronics_driver.h
- include/enrico/openmc_driver.h
- src/cell_instance.cpp
- src/nek_driver.cpp
- src/openmc_driver.cpp
- src/openmc_heat_driver.cpp
- src/openmc_nek_driver.cpp
- src/surrogate_heat_driver.cpp
- src/vtk_viz.cpp
Currently for coupling with OpenMC, we set up a tally with a material filter for each region that expects to see heat deposited. This requires that the OpenMC model use a unique material in each region, even if they have the same composition. However, OpenMC now has a new "cell instance" filter that allows us to circumvent this limitation -- the filter allows a user to tally specific instances of a cell that is repeated in a geometry regardless of what material is used in them.
Some other updates in here:
- Fixed/updated some of the documentation
- Replaced variable-length arrays with std::vector (VLAs are not part of the C++ standard and are only supported through compiler extensions)
- Removed gsl-lite submodule since we now get it transitively through OpenMC
> Use cell instance filter for coupling with OpenMC

- include/enrico/driver.h
- include/enrico/heat_fluids_driver.h
- include/enrico/message_passing.h
- include/enrico/nek_driver.h
- include/enrico/neutronics_driver.h
- include/enrico/openmc_nek_driver.h
- include/smrt/shift_nek_driver.h
- src/heat_fluids_driver.cpp
- src/main.cpp
- src/message_passing.cpp
- src/nek_driver.cpp
- src/openmc_nek_driver.cpp
- src/smrt/shift_nek_driver.cpp
In our `OpenmcNekDriver`, we commonly use `MPI_Gatherv` to take a local quantity in Nek that is distributed over all ranks and gather it only the root process. The primary change in this PR is to collect that logic into a single method (`HeatFluidsDriver::gather`). This method is also templated based on the datatype that is being communicated. Altogether this required/inspired other associated changes:
- I've extracted `get_mpi_type<T>()` from ShiftNekDriver and placed it in our message_passing module
- `position_mpi_datatype` is now a global variable and is initialized separately from the drivers themselves
- `local_counts_` and `local_displs_` is now owned by the `HeatFluidsDriver` class
- `HeatFluidsDriver` now has new abstract methods (`temperature_local`, `density_local`, etc.) that …
> Factor out common communication pattern in OpenmcNekDriver

- include/enrico/comm.h
- src/coupled_driver.cpp
- src/message_passing.cpp
- src/openmc_driver.cpp
- src/openmc_nek_driver.cpp
This PR adds overloads to `Comm::broadcast` so it can handle a scalar or `xtensor`.  
For an `xtensor`, the non-root's destination buffer is resized according to the root send buffer's shape (and not simply according to its size).
> Scalar and xtensor overloads for Comm::broadcast

- CMakeLists.txt
- include/enrico/comm.h
- include/enrico/comm_split.h
- include/enrico/driver.h
- include/enrico/heat_fluids_driver.h
- include/enrico/mpi_types.h
- include/enrico/neutronics_driver.h
- include/enrico/openmc_nek_driver.h
- include/smrt/shift_nek_driver.h
- src/comm_split.cpp
- src/main.cpp
- src/mpi_types.cpp
- src/openmc_heat_driver.cpp
- src/openmc_nek_driver.cpp
- src/smrt/shift_nek_driver.cpp
This replaces #81 with a more limited set of changes:
* `Comm` has a `free()` member function
* Declarations from `message_passing.h` have been split into `comm_split.h` and `mpi_types.h` (and likewise for the definitions).  This  solved circular dependencies that I couldn't resolve with forward declarations.  
* `get_node_comms` uses `Comm`s for clarity.
> Comm split func

- src/smrt/shift_nek_driver.cpp
Looks like #88 missed a change on instantiating `NekDriver` from `ShiftNekDriver` to omit the `pressure_bc` parameter (and change the XML node being passed). This results in the build currently breaking is SCALE is enabled. This PR fixes that.
> Fix bug in instantiation of NekDriver from ShiftNekDriver

- CMakeLists.txt
- include/enrico/comm.h
- include/enrico/comm_split.h
- include/enrico/coupled_driver.h
- include/enrico/heat_fluids_driver.h
- src/comm_split.cpp
- src/coupled_driver.cpp
- tests/disjoint_bcast_debug/main.cpp
- tests/disjoint_comm_demo/enrico.xml
- tests/disjoint_comm_demo/main.cpp
This PR allows the heat and neutronics drivers to run on arbitrarily disjoint or overlapping communicators.  The communication scheme is the same, no matter if the communicators are fully overlapping, partially overlapping, or fully disjoint.  
The communicators are created in `get_driver_comms`: 
* Given two numbers each for number-of-nodes and procs-per-node, It creates two new communicators.  Once consists of "left-hand" nodes (based on an arbitrary node index, determined at runtime) and the other consists of right-hand nodes.  
* It also returns the internode comms, but these are not currently used in `CoupledDriver`.
`Comm` has a new set of templated member functions, `sendrecv_replace`, which are used in `CoupledDriver` to transfer data between the heat comm's root and the neutron …
> Disjoint Communicators

- doc/source/input.rst
- include/enrico/coupled_driver.h
- src/coupled_driver.cpp
Right now, our under-relaxation on coupled fields relies on a fixed factor. This PR allows the user to select a special value (`"robbins-monro"`) that will use the Robbins-Monro algorithm in choosing an under-relaxation factor. Namely, the value chosen is 1/n where n is the index of iteration (starting at 1), so as the simulation proceeds, the update asymptotically goes to being fully damped.
One other improvement: the user can now select the norm used on the temperature for convergence checks.
> Add option for Robbins-Monro relaxation

- include/enrico/coupled_driver.h
- include/enrico/neutronics_driver.h
- include/enrico/openmc_driver.h
- src/coupled_driver.cpp
- src/openmc_driver.cpp
There's a built-in assumption in much of our code that the "cell handles" that the neutronics driver returns start sequentially from zero. This pull request makes some progress in avoiding this assumption by changing how we iterate over the `cell_to_elems_` member in `CoupledDriver`. Rather than iterating from `0 ... cell_to_elems_.size() - 1`, we now just rely on range-based iterators provided by `unordered_map`.
A few other small tweaks in this PR:
- Introduce a `cell_label` abstract method for neutronics drivers. This avoids one remaining piece of the `CoupledDriver` logic where we access OpenMC internals, instead deferring to this new abstract method for the driver to provide what is needed.
- Along the same lines, all data members of `OpenmcDriver` are now private.
> Improve iteration over cell-element mappings 

- include/enrico/coupled_driver.h
- include/enrico/heat_fluids_driver.h
- include/enrico/nek_driver.h
- include/enrico/surrogate_heat_driver.h
In a few places, we declared constructors with > 1 parameter as `explicit`.  This PR omits the unnecessary declarations
> Removed some unnecessary `explicit` declarations

- src/coupled_driver.cpp
- src/nek_driver.cpp
- src/surrogate_heat_driver.cpp
This cleans up `NekDriver` by pushing the one-off adjustment further down into the API.  `NekDriver::temperature_at`, `NekDriver::set_heat_source_at`, etc., are now called with 0-based indices.  Then when the Nek interface functions (defined in Fortran) are called, the indices are increased by 1 in the argument lists.  
Importantly, it also updates a for loop in `CoupledDriver::update_heat_source` that used 1-based indexing.  The change was propagated to `SurrogateHeatDriver::set_heat_source_at`.  
Fixes #101
> Cleaned-up C -> Fortran indexing in NekDriver and CoupledDriver

- doc/source/input.rst
- src/coupled_driver.cpp
In the docs for `enrico.xml`, the allowed values for `<temperature_ic>` and `<density_ic>` were listed incorrectly.  The allowed value for the heat/fluid driver should be "heat_fluids" instead of "heat".
> Temperature_ic, density_ic vals from XML

- ci/test_singlerod_openmc_nekrs.sh
This updates the NekRS submodule to pull specific commit hashes of OCCA and Nek5000.  Upstream NekRS pulls OCCA and Nek5000 from their respective master branches at configure time; however, this introduced some version skew that broke the builds.  By pulling from specific commit hashes (rather than branches) we should be able to avoid this version skew.
> Update NekRS submodule; run nrspre in CI

- tests/singlerod/short/nekrs/rod_short.oudf
- tests/singlerod/short/nekrs/rod_short.usr
As discussed a few times in calls, the z velocity in the shortrod model should be 50 cm/s, not 25 cm/s. I've also removed the `userbc` routine that is superseded by the oudf file.
> Fix z velocity in shortrod NekRS model

- src/vtk_viz.cpp
Fixes the VTK output for the surrogate source term. The source term is a 4-D array (pin, axial level, radial ring, azimuthal sector) but was being accessed using only the 3 leading dimensions, resulting in incorrect output.
> Fix VTK source output.

- include/enrico/shift_driver.h
- src/shift_driver.cpp
Corrects use of cell index in calls to Shift functions. The ENRICO cell handle was being passed instead of the Shift cell index. Also changes the variable names to reflect the distinction between handles and cell indices.
> Use cells rather than cell handles in Shift calls.

- .github/workflows/ci.yml
The `ubuntu-latest` in the GitLab CI runners have swtiched from Ubuntu 18 to 20.  The MPICH distribution in Ubuntu 20 requires the evn variable `MPICH_FC=gfortran` to configure Nek5000 properly.  This PR adds that env variable.
> MPICH_FC in GitLab CI

- .gitignore
- README.md
- scripts/bsub_enrico_summit.py
This adds a Python script for running ENRICO with NekRS on Summit.  The script does pre-compilation of NekRS kernels (which can be optionally skipped) and submits the job via `bsub`.  
The general usage of the script is this (available from `--help` and documented in the README.md file):
```
usage: bsub_enrico_summit.py [-h] -n NODES -t TIME [-b {CUDA,SERIAL}]
[--no-precompile]
optional arguments:
-h, --help            show this help message and exit
-n NODES, --nodes NODES
Specify the number of NODES (not processes) to use
-t TIME, --time TIME  Sets the runtime limit of the job
-b {CUDA,SERIAL}, --backend {CUDA,SERIAL}
Sets the OCCA kernel backend [default: CUDA]
--no-precompile       Skips pre-compile step for NekRS kernels
```
Most of the runtime parameters come from [`nrsqsub_summit` …
> Added script for running on Summit

- src/nekrs_driver.cpp
This removes an incorrect barrier in `NekRSDriver`.   It fixes coupled neutronics/nekRS runs with disjoint communicators.  
The nekRS driver's comm was passed to the barrier function.  However, the barrier function is called by all the ranks in the coupled driver's comm, including the ranks that are not active in the nekRS driver's comm.  In runs with disjoint comms, this causes MPI errors due to an invalid comm in the `MPI_Barrier` call.
> Remove wrong barrier in NekRSDriver

- doc/source/userguide/input.rst
- include/enrico/comm.h
- include/enrico/coupled_driver.h
- src/coupled_driver.cpp
This adds a verbosity setting for the `CoupledDriver`.  
Verbosity is "false" by default.  If "false", this output is suppressed:
* Communicator layout for each rank
* Volume comparisons for each neutronics cell
If "true", those outputs are shown (as in the current master branch).   
Summary statistics for the volume comparisons are always printed (this is a new feature).  For each cell, the relative difference between the neutronics driver's volume and the volume accumulated from heat/fluids elements is calculated.  Then the min, max, and mean of the relative differences are reported.
> Verbosity setting for coupled driver

- CMakeLists.txt
- include/enrico/driver.h
- src/coupled_driver.cpp
- src/nekrs_driver.cpp
- src/openmc_driver.cpp
- src/shift_driver.cpp
This is a workaround for the fact that nekRS forces the number of OpenMP threads to be 1:
https://github.com/Nek5000/nekRS/blob/d955b9b75cf50ca525dfc2f9c5a38e8c622e5d59/src/core/utils/occaHelpers.cpp#L92-L93 
The nekRS devs confirmed that this will be removed in upcoming versions.  At that point, we should be able to revert this PR.
In this PR:
* Each single-physics driver discovers the number of OpenMP threads at the end of its constructor.  It sets the num threads to a data member, `num_threads`
* In the coupled driver, the number of threads is toggled directly before each single-physics driver executes.
> Toggle num threads before single-physics driver execute

- doc/source/requirements.txt
The recent version of docutils, v18.0, is not compatible with readthdocs builds.  See:  https://github.com/readthedocs/readthedocs.org/issues/8616
This PR pins the version of docutils to < 18.0
> pin docutils version for readthdocs.io

- doc/source/methodology/cell_avg.rst
- doc/source/methodology/comm_split.rst
I noticed a few typos in our documentation which are fixed in this PR.
> Fix a few typos in documentation

- .gitignore
- CMakeLists.txt
- include/enrico/neutronics_driver.h
- include/enrico/openmc_driver.h
- include/enrico/surrogate_heat_driver.h
- src/comm_split.cpp
- src/coupled_driver.cpp
- src/heat_fluids_driver.cpp
- src/nek5000_driver.cpp
- src/openmc_driver.cpp
- src/shift_driver.cpp
- vendor/iapws/iapws.cpp
The goal of this change is to find OpenMC if it is already installed and use that instead of the submodule. Updates also include a change to the `gsl` headers that are included throughout the code. That is both a best practice now and also necessary for this change to work.
I believe this should address #152.
> Use installed OpenMC if available

- .vscode/settings.json
- CMakeLists.txt
- doc/source/userguide/input.rst
- include/enrico/boron_driver.h
- include/enrico/cell_handle.h
- include/enrico/comm.h
- include/enrico/const.h
- include/enrico/coupled_driver.h
- include/enrico/driver.h
- include/enrico/neutronics_driver.h
- include/enrico/openmc_driver.h
- include/enrico/shift_driver.h
- src/boron_driver.cpp
- src/coupled_driver.cpp
- src/openmc_driver.cpp
- tests/singlerod/make_openmc_model.py
- tests/singlerod/openmc_boron_heat_surrogate/enrico.xml
- tests/singlerod/openmc_boron_heat_surrogate/geometry.xml
- tests/singlerod/openmc_boron_heat_surrogate/materials.xml
- tests/singlerod/openmc_boron_heat_surrogate/settings.xml
This PR completes the critical boron search driver implementation started by @mekiel-sudo.  This capability is added with a BoronDriver class that is an attribute of the CoupledDriver class. 
This capability performs the following actions:
1. Gathers user input from the ``<neutronics>`` block of enrico.xml:
a. The capability is enabled with the boolean ``boron_search`` element.  
b. When enabled, the following elements apply: ``initial_boron_ppm, target_keff, target_keff_tolerance, B10_enrichment, and boron_epsilon``.
2. The HeatDriver's knowledge of which cells are fluid bearing is communicated to the BoronDriver's processors. 
3. The initial boron conditions are set or determined, depending on the setting of the ``initial_boron_ppm`` parameter.
4. For each picard iteration the following …
> Implementation of Boron Driver

- .github/workflows/ci.yml
- ci/download_xs.sh
I recently updated the cross sections libraries for OpenMC due to a bug (described in full [here](https://github.com/openmc-dev/data/issues/77)). Along with that update, the directory name in the tarball changed, so this PR simply updates the directory name used in the tests that require running OpenMC.
> Update data directory for OpenMC cross sections
